public class FileManager(string output, string changeResultFile)
{
    public void DebugDeleteAll()
    {
        var outputDir = Directory.CreateDirectory(output);

        // Clean previous generated files
        foreach (var old in outputDir.GetFiles("*.cs"))
            old.Delete();
        foreach (var old in outputDir.GetDirectories("*"))
            old.Delete(true);
    }

    public async Task WriteFiles(ArtifactGenerator.ArtifactItem[] artifacts)
    {
        var outputDir = Directory.CreateDirectory(output);

        var previousFiles = outputDir.GetFiles("*.*", SearchOption.AllDirectories)
            .Select(f => f.FullName.Replace('\\', '/'))
            .ToHashSet();

        var writed = 0;
        var passed = 0;

        async Task WriteFileIfChanged(string fileName, string directoryPath, string code)
        {
            var outputPath = Path.Combine(directoryPath, fileName).Replace('\\', '/');

            previousFiles.Remove(outputPath);

            if (File.Exists(outputPath))
            {
                var oldContent = await File.ReadAllTextAsync(outputPath);
                if (ArtifactGenerator.GetComparableCode(code) == ArtifactGenerator.GetComparableCode(oldContent))
                {
                    Console.WriteLine($"   ~ {outputPath[outputDir.FullName.Length..]}");
                    passed++;
                    return;
                }
            }

            Directory.CreateDirectory(directoryPath);

            await File.WriteAllTextAsync(outputPath, code);
            Console.WriteLine($"   + {outputPath[outputDir.FullName.Length..]}");
            writed++;
        }

        foreach (var (Artifact, Filename, directory, Endpoint) in artifacts)
        {
            var directoryPath = Path.Combine(outputDir.FullName, directory);

            await WriteFileIfChanged(
                $"{Filename}.cs",
                directoryPath,
                GetFileHeader([]) + '\n' + Artifact.Code
            );

            await WriteFileIfChanged(
                $"{Filename}.Endpoint.cs",
                directoryPath,
                BuildEndpointPartial(Artifact.TypeName, Endpoint)
            );
        }

        await WriteFileIfChanged(
            $"PokeApiJsonContext.cs",
            outputDir.FullName,
            BuildJsonContext(artifacts)
        );

        foreach (var path in previousFiles)
        {
            File.Delete(path);
            Console.WriteLine($"   - {path[outputDir.FullName.Length..]}");
        }

        Console.WriteLine();
        Console.WriteLine($"Files:");
        Console.WriteLine($"\t+ {writed} files generated");
        Console.WriteLine($"\t- {previousFiles.Count} files deleted");
        Console.WriteLine($"\t~ {passed} files not modified");

        await File.WriteAllTextAsync(changeResultFile, (writed + previousFiles.Count) > 0 ? "true" : "false");
    }

    private static string BuildEndpointPartial(string typeName, string endpoint) =>
        $$"""
        {{GetFileHeader([])}}
        public partial class {{typeName}}
        {
            /// <summary>PokeAPI/api-data file endpoint for this resource.</summary>
            public const string FileEndpoint = "{{endpoint}}";
            
            /// <summary>PokeAPI/api-data file list endpoint for this resource.</summary>
            public const string FileEndpointList = "{{GetListFileEndpoint(endpoint)}}";
            
            /// <summary>PokeAPI REST endpoint for this resource.</summary>
            /// <remarks>Replace {id} with a numeric ID or name to fetch a specific resource.</remarks>
            public const string RestEndpoint = "{{GetRESTEndpoint(endpoint)}}";
            
            /// <summary>PokeAPI REST list endpoint for this resource.</summary>
            public const string RestEndpointList = "{{GetRESTEndpoint(GetListFileEndpoint(endpoint))}}";
        }

        """;

    private static string GetFileHeader(string[] imports) => $"""
        // <auto-generated/>
        // File generated from PokeApi/api-data schemas.
        // Do not modify.
        {(imports.Length > 0
            ? $"\n{string.Join('\n', imports.Select(imp => $"using {imp};"))}\n"
            : "")}
        #nullable enable

        namespace {ArtifactGenerator.PackageNamespace};

        """;

    private static string GetRESTEndpoint(string fileEndpoint) => fileEndpoint
        .Replace("$id", "{id}")
        .Replace("index.json", "");

    private static string GetListFileEndpoint(string fileEndpoint) => fileEndpoint.EndsWith("$id/index.json")
        ? fileEndpoint[..(fileEndpoint.Length - "$id/index.json".Length)] + "index.json"
        : "";

    private static string BuildJsonContext(ArtifactGenerator.ArtifactItem[] artifacts) =>
        $$"""
        {{GetFileHeader(["System.Text.Json.Serialization"])}}
        {{string.Join('\n', artifacts.Select(entry => $"[JsonSerializable(typeof({entry.Artifact.TypeName}))]"))}}
        
        [JsonSourceGenerationOptions(
            PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
            PropertyNameCaseInsensitive = true
        )]
        public partial class PokeApiJsonContext : JsonSerializerContext
        {
        }

        """;
}