public class FileManager(string output, string changeResultFile)
{
    private static readonly string fileHeader = $"""
        // <auto-generated/>
        // File generated from PokeApi/api-data schemas.
        // Do not modify.

        #nullable enable

        namespace {ArtifactGenerator.PackageNamespace};

        """;

    public void DebugDeleteAll()
    {
        var outputDir = Directory.CreateDirectory(output);

        // Clean previous generated files
        foreach (var old in outputDir.GetFiles("*.cs"))
            old.Delete();
        foreach (var old in outputDir.GetDirectories("*"))
            old.Delete(true);
    }

    public async Task WriteFiles(ArtifactGenerator.ArtifactItem[] artifacts)
    {
        var outputDir = Directory.CreateDirectory(output);

        var previousFiles = outputDir.GetFiles("*.*", SearchOption.AllDirectories)
            .Select(f => f.FullName.Replace('\\', '/'))
            .ToHashSet();

        var writed = 0;
        var passed = 0;

        foreach (var (Artifact, Filename, directory, Endpoint) in artifacts)
        {
            var fileName = $"{Filename}.cs";
            var directoryPath = Path.Combine(outputDir.FullName, directory);
            var outputPath = Path.Combine(directoryPath, fileName).Replace('\\', '/');
            var content = fileHeader + '\n' + Artifact.Code;

            previousFiles.Remove(outputPath);

            var endpointFileName = $"{Filename}.Endpoint.cs";
            var endpointPath = Path.Combine(directoryPath, endpointFileName).Replace('\\', '/');
            var endpointContent = BuildEndpointPartial(Artifact.TypeName, Endpoint);

            previousFiles.Remove(endpointPath);

            if (File.Exists(outputPath) && File.Exists(endpointPath))
            {
                var oldContent = await File.ReadAllTextAsync(outputPath);
                var oldEndpointContent = await File.ReadAllTextAsync(endpointPath);
                if (ArtifactGenerator.GetComparableCode(content) == ArtifactGenerator.GetComparableCode(oldContent)
                    && ArtifactGenerator.GetComparableCode(endpointContent) == ArtifactGenerator.GetComparableCode(oldEndpointContent)
                )
                {
                    Console.WriteLine($"   ~ {outputPath[outputDir.FullName.Length..]}");
                    passed++;
                    Console.WriteLine($"   ~ {endpointPath[outputDir.FullName.Length..]}");
                    passed++;
                    continue;
                }
            }

            Directory.CreateDirectory(directoryPath);

            await File.WriteAllTextAsync(outputPath, content);
            Console.WriteLine($"   + {outputPath[outputDir.FullName.Length..]}");
            writed++;

            await File.WriteAllTextAsync(endpointPath, endpointContent);
            Console.WriteLine($"   + {endpointPath[outputDir.FullName.Length..]}");
            writed++;

        }

        foreach (var path in previousFiles)
        {
            File.Delete(path);
            Console.WriteLine($"   - {path[outputDir.FullName.Length..]}");
        }

        Console.WriteLine();
        Console.WriteLine($"Files:");
        Console.WriteLine($"\t+ {writed} files generated");
        Console.WriteLine($"\t- {previousFiles.Count} files deleted");
        Console.WriteLine($"\t~ {passed} files not modified");

        await File.WriteAllTextAsync(changeResultFile, (writed + previousFiles.Count) > 0 ? "true" : "false");
    }

    private static string BuildEndpointPartial(string typeName, string endpoint) =>
        $$"""
        {{fileHeader}}
        public partial class {{typeName}}
        {
            /// <summary>PokeAPI/api-data file endpoint for this resource.</summary>
            public const string FileEndpoint = "{{endpoint}}";
            
            /// <summary>PokeAPI/api-data file list endpoint for this resource.</summary>
            public const string FileEndpointList = "{{GetListFileEndpoint(endpoint)}}";
            
            /// <summary>PokeAPI REST endpoint for this resource.</summary>
            /// <remarks>Replace {id} with a numeric ID or name to fetch a specific resource.</remarks>
            public const string RestEndpoint = "{{GetRESTEndpoint(endpoint)}}";
            
            /// <summary>PokeAPI REST list endpoint for this resource.</summary>
            public const string RestEndpointList = "{{GetRESTEndpoint(GetListFileEndpoint(endpoint))}}";
        }

        """;

    private static string GetRESTEndpoint(string fileEndpoint) => fileEndpoint
        .Replace("$id", "{id}")
        .Replace("index.json", "");

    private static string GetListFileEndpoint(string fileEndpoint) => fileEndpoint.EndsWith("$id/index.json")
        ? fileEndpoint[..(fileEndpoint.Length - "$id/index.json".Length)] + "index.json"
        : "";
}