using NJsonSchema;
using NJsonSchema.CodeGeneration;
using NJsonSchema.CodeGeneration.CSharp;

Console.WriteLine("- Schema Generator -");

var input = args[0];
var output = args[1];
var changeResultFile = args[2];

Console.WriteLine($"Input : {input}");
Console.WriteLine($"Output : {output}");
Console.WriteLine($"Change result file : {changeResultFile}");
Console.WriteLine();

var packageNamespace = "PokeApi.Models";

var schemaRoot = new DirectoryInfo(input);

var schemaFiles = Directory.GetFiles(input, "*.json", SearchOption.AllDirectories)
    .Order()
    .ToList();

if (schemaFiles.Count == 0)
{
    throw new ArgumentException("No JSON file found");
}

Console.WriteLine($"{schemaFiles.Count} schemas found");

var outputDir = Directory.CreateDirectory(output);

var schemas = new List<JsonSchema>();
var loadErrors = new List<string>();

foreach (var schemaFile in schemaFiles)
{
    var schema = await JsonSchema.FromFileAsync(
        schemaFile,
        rootSchema => new PokeApiReferenceResolver(rootSchema, schemaRoot.FullName));
    schemas.Add(schema);
}

var settings = new CSharpGeneratorSettings
{
    Namespace = packageNamespace,
    ClassStyle = CSharpClassStyle.Poco,
    GenerateDataAnnotations = false,
    GenerateNullableReferenceTypes = true,
    GenerateOptionalPropertiesAsNullable = true,
    GenerateDefaultValues = true,
    HandleReferences = true,
    JsonLibrary = CSharpJsonLibrary.SystemTextJson,
    PropertyNameGenerator = new PascalCasePropertyNameGenerator(),
    TypeNameGenerator = new PascalCaseTypeNameGenerator(),
};

var allArtifacts = new List<CodeArtifact>();

foreach (var schema in schemas)
{
    var csharpGenerator = new CSharpGenerator(schema, settings);
    var artifacts = csharpGenerator.GenerateTypes(schema, "");
    allArtifacts.AddRange(artifacts);
}

// Dedupe by TypeName, handling case conflicts
var uniqueArtifacts = allArtifacts
    .GroupBy(a => a.TypeName)
    .Select(g => g.First())

    // handle case conflicts
    .GroupBy(a => a.TypeName.ToLower())
    .SelectMany(g =>
    {
        if (g.Count() > 1)
        {
            return g.Select((a, i) => (Artefact: a, Filename: $"{a.TypeName}{i}"));
        }

        return g.Select((a, i) => (Artefact: a, Filename: a.TypeName));
    })
    .OrderBy(v => v.Filename)
    .ToList();

Console.WriteLine($"{uniqueArtifacts.Count} unique types ({allArtifacts.Count} defore dedupe)");
Console.WriteLine();

// Clean previous generated files
// foreach (var old in outputDir.GetFiles("*.cs"))
//     old.Delete();

string GetComparableCode(string raw)
{
    return string.Join('\n', raw.Split('\n')
        .Select(line => line.Trim())
        .Where(line => line.Length > 0 && !line.StartsWith("//"))
    );
}

var fileHeader = $"""
    // <auto-generated/>
    // Ce fichier a été généré automatiquement à partir des schemas JSON de PokeAPI.
    // Ne pas modifier manuellement.

    #nullable enable

    """;

var writed = 0;
var passed = 0;

foreach (var (Artifact, Filename) in uniqueArtifacts)
{
    var fileName = $"{Filename}.cs";
    var outputPath = Path.Combine(outputDir.FullName, fileName);
    var content = fileHeader + Artifact.Code;

    if (File.Exists(outputPath))
    {
        var oldContent = await File.ReadAllTextAsync(outputPath);
        if (GetComparableCode(content) == GetComparableCode(oldContent))
        {
            Console.WriteLine($"   ~ {fileName}");
            passed++;
            continue;
        }
    }

    await File.WriteAllTextAsync(outputPath, content);
    Console.WriteLine($"   + {fileName}");
    writed++;
}

// TODO remove extra old files if any

Console.WriteLine();
Console.WriteLine($"{writed} files generated / {passed} files not modified");

await File.WriteAllTextAsync(changeResultFile, writed > 0 ? "true" : "false");
